outline.server:
  host: host
  port: 1023
  key: YiSSP-HOknt1mM7vKiu4DA

spring:
  mvc.throw-exception-if-no-handler-found: true
  security.user.password: 123456

management.endpoints.web.exposure.include: env,health,httptrace,info,logfile,metrics,sessions,version
