outline.server:
  host: 127.0.0.1
  port: 1023
  key: YiSSP-HOknt1mM7vKiu4DA

spring:
  mvc.throw-exception-if-no-handler-found: true
  security.user.password: 123456

logging.level.com.testbird: INFO
logging.level.com.testbird.inline.controller: DEBUG

management.endpoints.web.exposure.include: env,health,httptrace,info,logfile,loggers,metrics,sessions,version
management.metrics.export.prometheus.step: 10m